"""Add category table

Revision ID: 11129e5788e9
Revises: 48c0808b3541
Create Date: 2022-01-20 09:12:59.777086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11129e5788e9'
down_revision = '48c0808b3541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
