"""Add category id on product

Revision ID: 932d39c3ae12
Revises: 11129e5788e9
Create Date: 2022-01-20 09:22:05.892789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932d39c3ae12'
down_revision = '11129e5788e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###
